name: Find MaccabiPedia Errors
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -e .
      - name: Fetch MaccabiPedia Data
        run: python src/maccabistats/github_actions_scripts/fetch_games_from_maccabipedia.py
      - name: Find Errors
        run: python src/maccabistats/github_actions_scripts/find_maccabipedia_errors.py
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y_%m_%d')"
      - name: Send Errors to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MACCABIPEDIA_ERRORS_TELEGRAM_TO }}
          token: ${{ secrets.MACCABIPEDIA_ERRORS_TELEGRAM_TOKEN }}
          message: New errors file
          document: ${{ steps.date.outputs.date }}__maccabipedia_errors.txt