name: Find MaccabiPedia Errors
on: [ push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: python -m pip install --upgrade pip
             pip install -e .
      - name: Fetch MaccabiPedia Data
        run: python src/maccabistats/github_actions_scripts/fetch_games_from_maccabipedia.py
      - name: Find Errors
        run: python src/maccabistats/github_actions_scripts/find_maccabipedia_errors.py